app:
  resource: '@AppBundle/Controller/'
  type: annotation
  
job_index:
  path: /
  defaults: { _controller: AppBundle:Job:index }
  
job_new: 
  path: /job/new
  defaults: { _controller: AppBundle:Job:new }

job_show: 
  path: /job/{company}/{location}/{id}/{position}
  defaults: { _controller: AppBundle:Job:show }  

job_edit: 
  path: /job/{token}/edit
  defaults: { _controller: AppBundle:Job:edit }  

job_delete: 
  path: /job/{token}/delete
  defaults: { _controller: AppBundle:Job:delete }

job_preview:
  path: /job/{company}/{location}/{token}/{position}
  defaults: { _controller: AppBundle:Job:admin }

job_publish:
  path: /job/{token}/publish
  defaults: { _controller: AppBundle:Job:admin }
  
category_show:
  path: /category/{slug}/{page}+
  defaults: { _controller: AppBundle:Category:show, page: 1 }


  