AppBundle\Entity\Affiliate:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AffiliateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
        email:
            type: string
            length: 255
        token:
            type: string
            length: 255
            unique: true
        isActive:
            type: boolean
            nullable: true
        createdAt:
            type: datetime
    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: affiliates
            joinTable:
                name: categories_affiliates
                joinColumns:
                    affiliate_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [ setCreatedAtValue ]
