AppBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
        company:
            type: string
            length: 255
        logo:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        position:
            type: string
            length: 255
        location:
            type: string
            length: 255
        description:
            type: text
        howToApply:
            type: text
        token:
            type: string
            length: 255
            unique: true
        isPublic:
            type: boolean
            nullable: true
        isActivated:
            type: boolean
            nullable: true
        email:
            type: string
            length: 255
        expiresAt:
            type: datetime
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        file:
            type: string
            lenght: 255
            nullable: true

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: jobs
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: 
        prePersist: [ setCreatedAtValue, setUpdatedAtValue, setExpiresAtValue ]
        preUpdate: [ setUpdatedAtValue ]
        
